### ISSUE TITLE
Nightly version Error

### ISSUE THREAD

**Issue by mustafahdurmaz** [AktugHakan/NinovaArsivci#4] opened 2022-10-15 19:49 UTC
After logging in and selecting a file, the program prompts me to log in again and gives an error.

Operating system I use: Windows 11

**Comment by AktugHakan** [comment] 2022-10-16 17:43
It works in Linux but not in Windows. It seems like the cause of error is how Windows handles multi-processes. I will check this out.

**Comment by AktugHakan** [comment] 2022-10-16 18:03
Fixed by checking __name__ magic variable.

**Closed as completed by AktugHakan** 2022-10-16 18:03 UTC
